#!/bin/bash
ionic generate page claim-management/claim-forms/social-forms/claimSocial1
ionic generate page claim-management/claim-forms/social-forms/claimSocial2
ionic generate page claim-management/claim-forms/social-forms/claimSocial3
ionic generate page claim-management/claim-forms/social-forms/claimSocial4
ionic generate page claim-management/claim-forms/social-forms/claimSocial5
ionic generate page claim-management/claim-forms/social-forms/claimSocial6
ionic generate page claim-management/claim-forms/social-forms/claimSocial7
ionic generate page claim-management/claim-forms/social-forms/claimSocial8
ionic generate page claim-management/claim-forms/social-forms/claimSocial9
ionic generate page claim-management/claim-forms/financial-forms/claimFinancial1
ionic generate page claim-management/claim-forms/financial-forms/claimFinancial2
ionic generate page claim-management/claim-forms/financial-forms/claimFinancial3
ionic generate page claim-management/claim-forms/financial-forms/claimFinancial4
ionic generate page claim-management/claim-forms/financial-forms/claimFinancial5
ionic generate page claim-management/claim-forms/financial-forms/claimFinancial6
ionic generate page claim-management/claim-forms/health-forms/claimHealth1
ionic generate page claim-management/claim-forms/health-forms/claimHealth2
ionic generate page claim-management/claim-forms/health-forms/claimHealth3
ionic generate page claim-management/claim-forms/health-forms/claimHealth4
ionic generate page claim-management/claim-forms/health-forms/claimHealth5
ionic generate page claim-management/claim-forms/health-forms/claimHealth6
